CREATE TABLE IF NOT EXISTS tbl_users (id_user int  GENERATED BY DEFAULT AS IDENTITY NOT NULL,
Login VARCHAR (255) NOT NULL,
id_role int NOT NULL, Password varchar(88) NOT NULL,
FirstName varchar(255), LastName varchar(255));

